docs/installation-java.md
docs/installation-node.md
docs/installation-python.md

PR Rookout/deployment-examples#27

Updated examples links for changes made 

---

docs/installation-node.md

Tested all the links I changed now - this is the only one I forgot.

Updated link

---

docs/installation-agent-proxy.md
docs/installation-agent.md
website/i18n/en.json

Fix issue #2007 - Broken link to remote agent.

Fix broken proxy link

---

docs/installation-node.md
docs/installation-python.md
docs/rooks-java.md
docs/rooks-node.md
docs/rooks-python.md
docs/troubleshooting-rooks.md
website/pages/en/troubleshooting.js

Ticket #1965
Rook setup, Rook reference, Rook troubleshooting
Java 7,8 (Oracle, OpenJDK)
Python 2.7, 3.5, 3.6, 3.7 (C-Python, Pypy)
Node 4.3, 6, 8, 10

updated rook version support

---

docs/installation-overview.md

Prompt user to log in to rookout app before creating a workspace

Minor bugfix

---

docs/installation-overview.md

-link in "log in to rookout ide"
-highlight call to action - move on to basic debugging
-improve copy for rook description

quick start comments

---

docs/node-getting-started.md

npm run tutorial in both Linux/Mac and Windows
fixed minor merge issues

agentless node tutorial leftovers

---

website/static/css/custom.css

Fixed logo text to wrap when screen is too small
Fix Rookout/Rookout#2275

Fixed logo to be aligned

---

website/siteConfig.js
website/static/js/rookoutCustom.js

Removed async/await use for maximum compatibility

Fixed token fetching to use our REST API endpoint

---

docs/agent.md

docs - agent configuration - send rookout data

---

docs/troubleshooting-rules.md

change path configuration

---

docs/java-getting-started.md
docs/node-getting-started.md
docs/python-getting-started.md

Updated java and python sandbox tutorials.

Sandboxes are now agentless

---

website/static/js/rookoutCustom.js

Add support for automatic tab switching depending on OS

---

docs/installation-overview.md

Fixed usage of tabs

---

docs/installation-overview.md
docs/sandbox-getting-started.md
website/static/js/rookoutCustom.js

Fix https://github.com/Rookout/Rookout/issues/2349

Show more info about org and org token

---

docs/installation-overview.md
docs/sandbox-getting-started.md
website/static/css/custom.css
website/static/css/docsearch.css

Fixed all bugs on mobile I could find.
If anyone sees something additional do tell :)
Fix Rookout/Rookout#2186

Mobile fixes

---

docs/rooks-setup.md

python uwsgi fork config

---

docs/rooks-setup.md

test rook connectivity

---

docs/rules-operations.md

text_file and json_file are agent only

---

docs/rules-operations.md

Slack and sumologic to saas

---

docs/rooks-setup.md

Source maps for node

---

docs/rooks-setup.md

updated rook docker snippets

---

docs/rules-operations.md

Document data redaction

---

docs/troubleshooting-rules.md

https://github.com/Rookout/Rookout/issues/2424
Will be merged into new rules page as well.

include externals in rookout file

---

docs/sandbox-getting-started.md

https://github.com/Rookout/Rookout/issues/2482

Update JVM cmds

---

docs/introduction.md

https://github.com/Rookout/Rookout/issues/2472

sandbox links in welcome page

---

docs/agent-setup.md

@Rookeret73 please let me know if you like it......

added update\restart\uninstall documentation

---

package-lock.json
website/i18n/en.json
website/package-lock.json
website/package.json
website/siteConfig.js
website/static/css/custom.css
website/static/css/docsearch.css
website/static/js/rookoutCustom.js

Fixed CSS for 1.5.1 breaking changes
Fix Rookout/Rookout#2534
Fix Rookout/Rookout#2561

Updated Docusaurus to 1.5.1

---

docs/agent-setup.md

pushing again due to irrelevant conflict in en.json

minor agent setup style fixes revisited

---

docs/rooks-setup.md

Fix https://github.com/Rookout/Rookout/issues/2527
@BenTheKlein FYI

Added JVM application detection workaround.

---

docs/workspaces-tagging.md
docs/workspaces.md

RK-141 - tags and workspaces revisited

---

.circleci/config.yml
website/build_utils/publish_release_notes.js
website/package.json

Added circleci jobs to create tags and publish releases

RK-272 - Added release note script

---

docs/workspaces-tagging.md

tagging minor fixes

---

website/siteConfig.js
website/static/js/rookoutCustom.js

Reverts Rookout/docs#171
Not working as it does not get the cookies from .rookout.com for some reason

Revert "Requesting org token from rest api only if rookout cookie exists RK-480"

---

docs/rooks-setup.md
docs/rules-reference.md

RK-483 Rook to rookout sdk

---

docs/agent-setup.md
docs/rules-reference.md

RK-511 - Agent to ETL Agent

---

docs/projects-tagging.md
docs/projects.md
docs/rules-structure.md
docs/sample-applications.md
docs/source-repos.md

RK-493 workspace to project leftovers

---

docs/breakpoints-status.md
docs/sample-applications.md

RK-611 merge minor spell fixes

---

docs/sdk-setup.md

Do not merge since rooks are not published yet
@orishavit WDYT about the java docs? i added the other start function; should i delete it?

RK-643 updated throw_errors

---

docs/breakpoints-reference.md

RK-715 - remove unnecessary comma

---

docs/sample-applications.md

Breakpoint editor in sample apps

---

docs/sdk-setup.md

This reverts commit e918042e497b3605ed61d072d34e5717e98e5b6f.

Revert "RK-1324 - Document labels (#191)"

---

docs/sdk-setup.md

Still not happy with the copy. Please let me know what you think.
RK-1316

Initial copy for startSync

---

docs/agent-setup.md
docs/license.md

Agent license page

---

docs/license.md
docs/sdk-digests.md
docs/sdk-setup.md
website/package-lock.json
website/sidebars.json
website/static/js/rookoutCustom.js

Only 1 issue, could not check fetching from get.rookout.com actually works because from localhost i get CORS blocked :(
@Rookeret73 Where do we want this? I put it in the Getting started section but it doesnt seem appropriate

RK-1677 RK-1765 - Dynamically load SDK hashes from google storage

---

docs/projects.md

RK-2088 - Update projects.md

---

docs/agent-setup.md
docs/breakpoints-status.md
docs/quick-start.md
docs/sample-applications.md
docs/sdk-digests.md
docs/sdk-setup.md
website/build_utils/sdk-digests-base.md
website/package-lock.json
website/package.json
website/static/css/code-blocks-buttons.css
website/static/css/custom.css

Page tabs are left with the old custom component due to native docusaurus not supporting tabs in tabs

RK-2034 Update docusaurus

---

docs/sample-applications.md
docs/sdk-setup.md
website/package-lock.json
website/package.json
website/static/css/custom.css

Make page-tabs completely separate than normal code tabs
Update docusaurus to 1.10

RK-2521 - Try to fix page tabs in docs

---

docs/sdk-setup.md

Corretto only has 8 & 11 builds atm

RK-2382 Update supported JVM versions

---

docs/breakpoints.md

RK-2737 - Fixes a typo in breakpoints.md

---

docs/sdk-setup.md

Value oriented copy forincluding sources

---

docs/projects-labels.md

RK-3566 - Update projects-labels.md

---

website/build_utils/deployment_examples_generator.js

RK-3592 - Fix generated deployment examples page having jenkins directory

---

docs/projects-labels.md

RK-4207 - added SDK label as environment

---

docs/breakpoints-tasks.md

Deleted old rate limiting documentation

RK-4399 - Deleted old rate limit

---

docs/breakpoints-status.md

changes exclamation point to triangles

RK-4970 - triangles rule

---

docs/jvm-setup.md

https://rookout.atlassian.net/browse/RK-4808

RK-4808 - Align JVM instructions in docs with the instructions in wizard

---

docs/breakpoints-status.md
docs/jvm-setup.md

removed any remains of java api from the docs, due to it being a bad way to integrate Rookout

RK-5175 - Remove java api

---

docs/breakpoints-conditional.md

updated the conditional breakpoint pages to align with these PRs:
https://github.com/Rookout/frontend/pull/1859
https://github.com/Rookout/frontend/pull/1858

RK-5394 - updated bp conditions page

---

.circleci/config.yml
website/package.json
website/pages/api/index.html
website/pages/website-redirect/index.html
website/siteConfig.js

@orishoshan merge only when the api.yaml is in production and fetchable

RK-5461 - Rest api documentation

---

docs/python-setup.md

getting in line with https://github.com/Rookout/Rookout/pull/3136

RK-5664 - added python 3.8  support

---

docs/dotnet-setup.md

@LiranLast it wont be so easy to solve - lets start with documenting this - and wait for someone to pay us

iis8 (RK-5786)

---

docs/dotnet-setup.md

RK-5900 - removed SDK from .net sidebar

---

docs/dotnet-setup.md
docs/jvm-setup.md

Should wait for the release of the rook before merging this

dotnet sources (RK-5910)

---

docs/jvm-setup.md

RK-6188 - commit -> revision

---

docs/breakpoints-status.md

see https://github.com/Rookout/frontend/pull/2220

RK-6618 - updated rate limiting phrasing

---

website/yarn.lock

RK-6625 - relock cause Snyk was pissed

---

docs/dotnet-setup.md
docs/jvm-setup.md
docs/node-setup.md
docs/python-setup.md

updating the docs to mention we support branch auto-fetching
following - https://github.com/Rookout/frontend/pull/2286

RK-6814 - branch auth-fetching

---

docs/open-tracing.md
website/sidebars.json

This is a draft of the open tracing documentation.
Please feel free to add comments about what else we should add / if you think we should add links to other sites explaining about open tracing.

RK-6946 - Adding open-tracing doc file.

---

docs/welcome.md

What do you think?
We'll also need some supporting screenshots and an architecture image.

RK-7200 - New welcome page

---

website/sidebars.json

BP structure page is irrelevant, I've deleted the link

RK-7315 - deleted BP structure page link

---

docs/breakpoints-tasks.md

maybe we should also remove the part about editing it?

RK-7420 - Ratelimit/updated defaults

---

docs/breakpoints-status.md

Add another comment about transpile level - RK-7655

---

docs/node-setup.md

Add comment about transpile level - RK-7655

---

docs/node-setup.md

RK-8404 - node sources env var

---

docs/breakpoints-tasks.md

https://github.com/Rookout/frontend/pull/2759

RK-8690 - change blacklist to exclude list

---

docs/python-setup.md

* Added "fork" parameter which had a description but was missing from the function.
* Re-ordered the parameters to match the function.

Added "fork" to python `start` method

---

docs/welcome.md

RK-9110 - Update welcome.md

---

docs/welcome.md

Changed the video URL to /embed/ to try to fix the origin problem

RK-9148 - Update welcome.md video origin

---

docs/breakpoints-reference.md

RK-9778 - Update breakpoints-reference.md

---

docs/etl-controller-config.md
docs/etl-controller-docker.md
docs/etl-controller-k8s.md

Some minor link fixes and wrote one more line

RK-10023 - Fixes after ETL Controller rewrite

---

docs/breakpoints-status.md

Images need to be updated by @noagoldman 
Need to confirm that JVM No code is under pending while python no code is under error

RK-9980 - Update breakpoints-status.md

---

website/static/img/screenshots/WarningBlack.svg

Added warning bp status icon with dark exclamation mark

RK-10086 - Add files via upload

---

docs/breakpoints-status.md

Updated warning breakpoint image

RK-10085 - Update breakpoints-status.md

---

docs/breakpoints-conditional.md

RK-10216 - Update breakpoints-conditional.md

---

docs/debug-session-setup.md
docs/jvm-setup.md
docs/live-logger.md
docs/node-setup.md
docs/use-cases.md
docs/welcome.md
website/package.json
website/sidebars.json
website/yarn.lock

First draft of the Live Logger documentation update.
Do not merge yet - the video link is pending an update and upload to the youtube channel.

RK-10245 - live logger first draft

---

docs/live-logger.md
docs/welcome.md

RK-10246 - update live logger video link

---

docs/go-setup.md
website/sidebars.json

RK-10458 - Create go-setup.md

---

docs/ruby-setup.md

Added bundler option
Added git folder info
Removed wip stuff

RK-11485 - Ruby docs improvements

---

docs/etl-controller-config.md
docs/node-setup.md

Added mangling info + webpack mangling
Small fix to the controller config page

RK-11863 - Webpack mangling

---

website/static/css/custom.css

Override the footer styles for social icons 
Hover on the icons and see the range of the click area by looking at the url chrome shows 
Insert screenshots here

Fix click area on social buttons

---

docs/dop-config.md

The values added to Kubernetes Configuration

RK-12550 - Added Service port and Service port TLS

---

docs/node-setup.md

Removed the line saying we support Node 8

RK-12604 - Remove node 8 support

---

docs/python-setup.md

re-added the threads config for uWSGI applications, and grouped special configuration use cases together.

RK-12772 - uWSGI re-add threads config

---

docs/java-container-tutorial.md

RK-12822 - Update java-container-tutorial.md

---

docs/dop-install.md

RK-12921 - Fix DOP org token format

---

docs/java-container-tutorial.md
docs/node-container-tutorial.md
docs/python-container-tutorial.md

Add indicators for a token's org for the container tutorials
Add missing quotes to arguments

RK-13011 - Add indicators for a token's org for the container tutorials

---

docs/dotnet-container-tutorial.md

RK-13068 - Fixed broken internal links

---

docs/breakpoints-status.md
docs/dop-config.md
docs/dop-intro.md
docs/etl-controller-config.md

Correct broken internal links.

RK-13119 - Update links

---

docs/dop-config.md
docs/etl-controller-config.md

Some values were on the DS page instead of the Controller

RK-13432 - Remove wrong values from DS

---

docs/node-setup.md

The live_logger API config was missing

RK-13490 - Add live_logger API (Node)

---

docs/dotnet-container-tutorial.md
docs/java-container-tutorial.md
docs/node-container-tutorial.md
docs/python-container-tutorial.md
docs/ruby-container-tutorial.md
docs/source-repos.md
website/build_utils/sdk-digests-base.md

Fix all issues from this report - https://docs.google.com/spreadsheets/d/12RhdxIdQ8EUTyI_t_yYF2vLjE9fAGylGf_LhH68p5Ow/edit#gid=0
https://rookout.slack.com/archives/C01SD6TB6CA/p1660856263589009

RK-13553 - Fix 404s

---

docs/node-setup.md
docs/python-setup.md

Add docs for python's ROOKOUT_SOURCES

RK-13584 - python sources

---

.circleci/config.yml

https://rookout.atlassian.net/browse/RK-13765
docusaurus@2.0.1 requires node > 16.4

Update circle ci node version to 16.4.2

---

website/src/css/custom.css

https://rookout.atlassian.net/browse/RK-13781

RK-13781 mobile view

---

website/jest.config.js
website/package.json
website/test/buildFiles.spec.js
website/yarn.lock

https://rookout.atlassian.net/browse/RK-13799
At sanity tests to validate the important files are always present in build

Rk 13799 add sanity tests to deployment process 

---

website/docusaurus.config.js

Updated the favicon to be pulled from the CDN, now using the new icon
Tested locally

RK-13818 - updated favicon

---

docs/breakpoint-limits.md
docs/dotnet-setup.mdx

https://rookout.atlassian.net/browse/RK-14091

Post upgrade UI fixes

---

docs/welcome.mdx
firebase.json

Redirect straight to welcome page.
Fix typo.

RK-14211 - redirect to welcome page

---

firebase.json

need to redirect to a folder and not the .html

RK-14212 - fix welcome redirect

---

docs/dotnet-setup.mdx
docs/go-setup.md
docs/jvm-setup.mdx
docs/node-setup.mdx
docs/python-setup.mdx
docs/ruby-setup.mdx

Added quiet mode flags to docs

RK-14353 Update quiet mode in docs

---

docs/breakpoints-status.md

The warning status description was wrong

RK-14439 - Warning status fix

---

node_modules/.yarn-integrity
website/package.json
website/yarn.lock

https://rookout.atlassian.net/browse/RK-14759

add resolutions to sub deps of the docs

---

docs/java-container-tutorial.md
website/docusaurus.config.js
website/static/js/rookoutCustom.js

Refactored the logic of the `rookoutCustom` script to make a bit more sense
Token insertion should now work properly. For this to work on page change, I had to employ a pretty hacky method, but it's the best I can do given the time constraint for this task
Refactored some more minor issues, like no syntax highlighting for `Dockerfile` code blocks
Tested locally

RK-14665 - More bugfixes with org token insertion + some refactors

---

website/package.json
website/yarn.lock

Fixed all the vulnerabilities found by Snyk for this repo 
Tested locally everything works as before

RK-17058 - Snyk vulnerability fixes

---

website/docusaurus.config.js
website/static/js/rookoutCustom.js

Config Logrocket and Analytics Fixes.
Redact the body from requests to graphql (in order to redact the token)

RK-17746 - Config Logrocket and Analytics Fixes

---

docs/java-container-tutorial.md
docs/jvm-setup.mdx
docs/sdk-digests.mdx
website/build_utils/sdk-digests-base.mdx

Better stable link using maven search api for JVM agent

RK-18854 - update maven link

---

docs/node-setup.mdx

Add Node 20 to supported versions

RK-20086 - Add Node 20 to Supported Versions
