Rookout/docs

docs/installation-java.md
docs/installation-node.md
docs/installation-python.md

Still missing, will be handled in #2356 :
-Rookout API for all three languages
-Lambda info for Python and Node
-Node dependencies
-Maven snippet for Java setup

Refresh rook documentation

---

docs/collaboration.md

According to the Slack brand guidelines all the mentions of Slack must be with a capital S

RK-4452 - Capitalized all the Slack mentions

---

docs/node-setup.md

It looks like this should be a dash instead of an underscore now.  rookout-check instead of rookout_check

RK-5304 - typo fix in node connectivity test

---

docs/welcome.md

instead of 2019 demo, the getting started page now links to new demo from one month ago.
https://www.youtube.com/watch?v=wPwXgGKP1L8

RK-5723 - updated the 'getting started page' to have the new demo

---

docs/jvm-setup.md

A minor fix to the `-javaagent` options.
--
From #296 it looks like the wizard may also need to be updated, but I wasn't sure where the source code was, so I wanted to let you know here there are also a couple of issues with the content of the wizard too:
* the double quotes appear as `”` instead of `"`
* the `JAVA_TOOL_OPTIONS` environment variable includes a line return, which may not be desirable:
``` 
export JAVA_TOOL_OPTIONS=“-javaagent:(pwd)/rook.jar 
-DROOKOUT_TOKEN=< ... token ... >”
```
I think this should probably be a single line, regular quotes (`"`) and `$(pwd)` instead of `(pwd)`, i.e.:
```
export JAVA_TOOL_OPTIONS="-javaagent:$(pwd)/rook.jar -DROOKOUT_TOKEN=< ... token ... >"
```

RK-6552 - Fix path to rook.jar in -javaagent options

---

docs/projects-labels.md

noticed there's no example for dotnet in the code snippets of the labels page, so I added one.

RK-6877 - dotnet code snippet for the labels page

---

docs/breakpoints-conditional.md

We hear repeating feedback from users regarding Conditions settings:
״I don’t understand the condition syntax״ (Rookout supports different lango for conditions)
״I don’t understand when I have a typo (in vars) in my conditions.
״Documentation didn’t help me to understand my error / doesn't match the UI״  
To improve our user's experience we decide to rewrite the documentation and clarify a few pain points:
1.Which syntax is supported
2.Which type of variables are supported in conditions
3.Different reasons for condition set up to fail (typo, wrong syntax, etc...)
4. Explanations about differences between the languages Rookouts support and other languages

RK-7304 - Conditions rewriting

---

.circleci/config.yml

getting sudo: easy_install: command not found in circleci
pip is already installed, so no need for it

RK-8376 - pip already there, easy_install is deprecated

---

docs/dotnet-setup.md

This is at the end of the doc file just to make sure we are not breaking compatibility

RK-9142 - dotnet revert source packaging

---

docs/dotnet-setup.md

Reverts Rookout/docs#426
Our aim is to keep the SDK pages as focused, short, and symmetrical as possible.
I don't think we need this info here - if it's important for the docs, let's add a separate page that covers it for all runtimes.

Revert "Dotnet - Docs on log file location (https://rookout.atlassian.net/browse/RK-9038)"

---

docs/dotnet-setup.md
docs/go-setup.md
docs/jvm-setup.md
docs/node-setup.md
docs/python-setup.md
docs/ruby-setup.md

Go SDK not available message.
Changed title of SDK pages.
Moved the .NET and JVM supported languages section to the top.

RK-11052 - SDK setup pages improvements

---

docs/jvm-setup.md

The current example won't work, as it mistakenly shows the ROOKOUT_TARGET_PID env var being set on the line IN FRONT of the java command. So first I have proposed removing that.
But then I've added an example that instead passes the needed env vars as java -D system properties. And note that I've added the -DROOKOUT_LABELS because in my testing of things, this would not work without it. (The injection would happen, but the site would never show a successful "connected application".)

RK-11243 - correct dynamic loading examples

---

docs/dotnet-setup.md
docs/jvm-setup.md
docs/node-setup.md
docs/python-setup.md

Removed GIT_COMMIT (need to make sure we have it documented internally)
Aligned the Source Info sections of some SDKs

RK-11248 - Remove GIT_COMMIT and improve source info

---

docs/python-setup.md

When clicking on the "For more info..." link in our Python SDK setup documentation and receives an error message 404-Page not found.

RK-12978 - Broken link

---

docs/ruby-setup.md

#clicks on the "For more info..." link in our Ruby SDK setup documentation and receives an error message 404-Page not found.

RK-12979 - RCS-676 - Update ruby-setup.md

---

docs/python-setup.md

Added celery and gunicorn explicitly as cases where you need to use fork=True

RK-12998 - Fork instructions for Celery, Gunicorn

---

docs/setup-guide.md

There is a broken link in the docs to https://www.rookout.com/faq/
If we intend to support FAQs I'll revert this change as soon as the page is live again.

RK-13094 - Remove broken link to FAQ

---

docs/dop-config.md

The docker part was missing the in-memory-db config.

RK-13477 - Add in-memory-db parameter to Docker specs

---

website/package.json

https://rookout.atlassian.net/browse/RK-13797
Copy api folder to one layer above to be available at [docs.rookout.com/api](http://docs.rookout.com/api)

RK-13797 restore missing api page

---

website/static/js/rookoutCustom.js

Fixed org tokens not being properly replaced for logged in users.
Also, simplified logic to require only one GQL query instead of two.
Tested locally.

RK-14665 - Fix token replacement

---

docs/go-setup.mdx

libc++-11 and libc++abi-11 is outdated for latest stable Debian "bookworm"
https://packages.debian.org/search?searchon=names&keywords=libc%2B%2B
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=libc%2B%2Babi

RK-19172 - debian-bookworm-libc

---

docs/go-setup.mdx

the two hyphen signs next to the "no -cache" are not the same (one of them appears different) causing an error

RK-19999 - Update go-setup.mdx
